dist: bionic
language: cpp
compiler: gcc

before_install:
  - sudo apt-get install qtbase5-dev qttools5-dev
  - export QT_SELECT=qt5

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --target install

before_deploy:
  - cd ..
  - LatestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
  - cd bin
  - tar -zcvf qt5_ci_test-$LatestTag-linux-x86_64.tar.gz

deploy:
  provider: releases
  api_key: $Token
  file: bin/qt5_ci_test-$LatestTag-linux-x86_64.tar.gz
  skip_cleanup: true
  on:
    tags: true
