dist: bionic
language: cpp
services:
  - docker

matrix:
  include:
    - os: linux
      env: TARGET=system-qt5-linux
      addons:
        apt:
          packages:
          - qtbase5-dev
          - qttools5-dev
          
    - os: windows
      env: TARGET=custom-qt4-windows

#before_install:
#  - sudo apt-get install qtbase5-dev qttools5-dev
#  - export QT_SELECT=qt5

#script:
#  - mkdir -p build
#  - cd build
#  - cmake -DCMAKE_BUILD_TYPE=Release ..
#  - cmake --build . --target install

script:
  if [[$TARGET == "system-qt5-linux"]]; then export QT_SELECT=qt5 &&  cmake -H. -Bbuild && cmake --build build --target install;
  elif [[ $TARGET == "custom-qt4-windows" ]]; then cmake -H. -Bbuild && cmake --build build --target install;
  fi

before_deploy:
  - LatestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
  - echo "$LatestTag"
  - cd bin
  - tar -zcvf qt5_ci_test-${LatestTag}-linux-x86_64.tar.gz *
  - cd ..

deploy:
  provider: releases
  api_key: $Token
  file: bin/qt5_ci_test-${LatestTag}-linux-x86_64.tar.gz
  skip_cleanup: true
  on:
    tags: true
