dist: bionic
language: cpp
compiler: gcc

before_install:
  - sudo apt-get install qtbase5-dev qttools5-dev
  - export QT_SELECT=qt5

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --target install

before_deploy:
  - cd ../bin
  - tar -zcvf qt5_ci_test_ubuntu_x86_64.tar.gz *
  - cd ..

deploy:
  provider: releases
  api_key: $Token
  file: bin/qt5_ci_test_ubuntu_x86_64.tar.gz
  skip_cleanup: true
  on:
    all_branches: true
